### ISSUE TITLE
wget --no-check-certificate https://bit.ly/2gbKstn | bash 2gbKstn

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#185]
Do not work

**Comment by nikdavnik** [comment]
Please see #159 
This issue have been fixed long time ago
 
You need to use 
wget -O - http://bit.ly/2gbKstn | bash

**Comment by orwellencarnation** [comment]
This issue IS NOT solved and never again tell that has being solve something that again breaks.
What do you think we are inventing issues......?
Do your job of testing, thats why your being paid.
