### ISSUE TITLE
Joakin Franko: The screen still goes to be disable by no activity.

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#283]
Could be this or the CPU temperature intrinsic to bios and not Linux itself?

**Comment by JFrancoJ** [comment]
This is absolutely not related with CPU throttle.
Is the terminal only. I fixed while the setup.sh doing setterm -blank 0
This issue happens on installation or after the reboot after installations and configurtion have been completed ?
If you want ALWAYS ( after installations and reboot ) the screen still always powered then I need to place the setterm -blank 0 also in initial scripts ( i.e. in /etc/rc.local )

**Comment by orwellencarnation** [comment]
After reboot both issues are still there, what im asking if this is BIOS config related both , not between them no digo que esten relacionadas entre ellas, si no con la configiracion de la bios, las dos.

**Comment by JFrancoJ** [comment]
ok, after reboot . Will add setterm -blank 0 to /etc/rc.local
No, la BIOS nada en éste caso, no es ACPI , es sólo el salvapantalla de 
la xterm que para el video.
Si se arregló durante instalacion, es lo mismo, solo que claro al 
rebootar hay que decirle de nuevo que no blank el terminal.


orwellencarnation wrote:

**Comment by JFrancoJ** [comment]
Probar cpupower con freq fija

**Comment by JFrancoJ** [comment]
Added setterm -blank 0 to rc.local
This must do console never comes blank

**Comment by orwellencarnation** [comment]
commited?

**Comment by JFrancoJ** [comment]
yes

orwellencarnation wrote:
